/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The error array that describe the errors got during the handling of request
type Errors struct {
	Errors []ModelError `json:"errors,omitempty"`
}
