/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectReq struct {
	// The name of the project.
	ProjectName string `json:"project_name,omitempty"`
	// deprecated, reserved for project creation in replication
	Public bool `json:"public,omitempty"`
	// The metadata of the project.
	Metadata *ProjectMetadata `json:"metadata,omitempty"`
	// The CVE allowlist of the project.
	CveAllowlist *CveAllowlist `json:"cve_allowlist,omitempty"`
	// The storage quota of the project.
	StorageLimit int64 `json:"storage_limit,omitempty"`
	// The ID of referenced registry when creating the proxy cache project
	RegistryId int64 `json:"registry_id,omitempty"`
}
