/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Platform struct {
	// The architecture that the artifact applys to
	Architecture string `json:"architecture,omitempty"`
	// The OS that the artifact applys to
	Os string `json:"os,omitempty"`
	// The version of the OS that the artifact applys to
	OsVersion string `json:"&#39;os.version&#39;,omitempty"`
	// The features of the OS that the artifact applys to
	OsFeatures []string `json:"&#39;os.features&#39;,omitempty"`
	// The variant of the CPU
	Variant string `json:"variant,omitempty"`
}
