/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProjectScanner struct {
	// The identifier of the scanner registration
	Uuid string `json:"uuid,omitempty"`
}
