/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type QuotaUpdateReq struct {
	// The new hard limits for the quota
	Hard *ResourceList `json:"hard,omitempty"`
}
