/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The quota object
type Quota struct {
	// ID of the quota
	Id int32 `json:"id,omitempty"`
	// The reference object of the quota
	Ref *QuotaRefObject `json:"ref,omitempty"`
	// The hard limits of the quota
	Hard *ResourceList `json:"hard,omitempty"`
	// The used status of the quota
	Used *ResourceList `json:"used,omitempty"`
	// the creation time of the quota
	CreationTime string `json:"creation_time,omitempty"`
	// the update time of the quota
	UpdateTime string `json:"update_time,omitempty"`
}
