/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AdminJobSchedule struct {
	Schedule *AdminJobScheduleObj `json:"schedule,omitempty"`
	// The parameters of admin job
	Parameters map[string]bool `json:"parameters,omitempty"`
}
