/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The CVE Allowlist for system or project
type CveAllowlist struct {
	// ID of the allowlist
	Id int32 `json:"id,omitempty"`
	// ID of the project which the allowlist belongs to.  For system level allowlist this attribute is zero.
	ProjectId int32 `json:"project_id,omitempty"`
	// the time for expiration of the allowlist, in the form of seconds since epoch.  This is an optional attribute, if it's not set the CVE allowlist does not expire.
	ExpiresAt int32 `json:"expires_at,omitempty"`
	Items []CveAllowlistItem `json:"items,omitempty"`
}
