/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RetentionRuleTrigger struct {
	Kind string `json:"kind,omitempty"`
	Settings *interface{} `json:"settings,omitempty"`
	References *interface{} `json:"references,omitempty"`
}
