/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
	// The ID of the user.
	UserId int32 `json:"user_id,omitempty"`
	Username string `json:"username,omitempty"`
	Email string `json:"email,omitempty"`
	Password string `json:"password,omitempty"`
	Realname string `json:"realname,omitempty"`
	Comment string `json:"comment,omitempty"`
	Deleted bool `json:"deleted,omitempty"`
	RoleName string `json:"role_name,omitempty"`
	RoleId int32 `json:"role_id,omitempty"`
	SysadminFlag bool `json:"sysadmin_flag,omitempty"`
	// indicate the admin privilege is grant by authenticator (LDAP), is always false unless it is the current login user
	AdminRoleInAuth bool `json:"admin_role_in_auth,omitempty"`
	ResetUuid string `json:"reset_uuid,omitempty"`
	Salt string `json:"Salt,omitempty"`
	CreationTime string `json:"creation_time,omitempty"`
	UpdateTime string `json:"update_time,omitempty"`
}
