/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SysAdminFlag struct {
	// true-admin, false-not admin.
	SysadminFlag bool `json:"sysadmin_flag,omitempty"`
}
