/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RetentionRule struct {
	Id int32 `json:"id,omitempty"`
	Priority int32 `json:"priority,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
	Action string `json:"action,omitempty"`
	Template string `json:"template,omitempty"`
	Params map[string]interface{} `json:"params,omitempty"`
	TagSelectors []RetentionSelector `json:"tag_selectors,omitempty"`
	ScopeSelectors map[string][]RetentionSelector `json:"scope_selectors,omitempty"`
}
